// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PredictLottoNZ.Data;

#nullable disable

namespace PredictLottoNZ.Migrations
{
    [DbContext(typeof(LottoDbContext))]
    [Migration("20251212013947_AddAdvancedLLMEntities")]
    partial class AddAdvancedLLMEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PredictLottoNZ.Models.ExternalServiceCallLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("RequestPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponsePayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_ExternalServiceCallLogs_CreatedAt");

                    b.HasIndex("ServiceName")
                        .HasDatabaseName("IX_ExternalServiceCallLogs_ServiceName");

                    b.HasIndex("Success")
                        .HasDatabaseName("IX_ExternalServiceCallLogs_Success");

                    b.HasIndex("ServiceName", "CreatedAt")
                        .HasDatabaseName("IX_ExternalServiceCallLogs_ServiceName_CreatedAt");

                    b.ToTable("ExternalServiceCallLogs");
                });

            modelBuilder.Entity("PredictLottoNZ.Models.LottoDraw", b =>
                {
                    b.Property<int>("Draw")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Draw"));

                    b.Property<int>("BonusNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Division1Prize")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("Division1Winners")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Division2Prize")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("Division2Winners")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Division3Prize")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("Division3Winners")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Division4Prize")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("Division4Winners")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Division5Prize")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("Division5Winners")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Division6Prize")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("Division6Winners")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Division7Prize")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("Division7Winners")
                        .HasColumnType("integer");

                    b.Property<int?>("ElevenToTwenty")
                        .HasColumnType("integer");

                    b.Property<int?>("Even")
                        .HasColumnType("integer");

                    b.Property<string>("FromLast")
                        .HasColumnType("text");

                    b.Property<int?>("High")
                        .HasColumnType("integer");

                    b.Property<int?>("Low")
                        .HasColumnType("integer");

                    b.Property<int?>("Odd")
                        .HasColumnType("integer");

                    b.Property<int?>("OneToTen")
                        .HasColumnType("integer");

                    b.Property<int>("Powerball")
                        .HasColumnType("integer");

                    b.Property<int?>("ThirtyOneToForty")
                        .HasColumnType("integer");

                    b.Property<int?>("TwentyOneToThirty")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WinningNumber1")
                        .HasColumnType("integer");

                    b.Property<int>("WinningNumber2")
                        .HasColumnType("integer");

                    b.Property<int>("WinningNumber3")
                        .HasColumnType("integer");

                    b.Property<int>("WinningNumber4")
                        .HasColumnType("integer");

                    b.Property<int>("WinningNumber5")
                        .HasColumnType("integer");

                    b.Property<int>("WinningNumber6")
                        .HasColumnType("integer");

                    b.HasKey("Draw");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_LottoDraws_CreatedAt");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_LottoDraws_Date");

                    b.ToTable("LottoDraws");
                });

            modelBuilder.Entity("PredictLottoNZ.Models.ModelVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeployedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModelPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ModelVersionNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("ValidationAccuracy")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_ModelVersions_CreatedAt");

                    b.HasIndex("DeployedAt")
                        .HasDatabaseName("IX_ModelVersions_DeployedAt");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_ModelVersions_IsActive");

                    b.HasIndex("ProviderName")
                        .HasDatabaseName("IX_ModelVersions_ProviderName");

                    b.HasIndex("ProviderName", "IsActive")
                        .HasDatabaseName("IX_ModelVersions_ProviderName_IsActive");

                    b.ToTable("ModelVersions");
                });

            modelBuilder.Entity("PredictLottoNZ.Models.NumberCombination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Number1")
                        .HasColumnType("integer");

                    b.Property<int>("Number2")
                        .HasColumnType("integer");

                    b.Property<int>("Number3")
                        .HasColumnType("integer");

                    b.Property<int>("Number4")
                        .HasColumnType("integer");

                    b.Property<int>("Number5")
                        .HasColumnType("integer");

                    b.Property<int>("Number6")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_NumberCombinations_CreatedAt");

                    b.HasIndex("Number1", "Number2", "Number3", "Number4", "Number5", "Number6")
                        .HasDatabaseName("IX_NumberCombinations_Numbers");

                    b.ToTable("NumberCombinations");
                });

            modelBuilder.Entity("PredictLottoNZ.Models.Prediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("ConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Number1")
                        .HasColumnType("integer");

                    b.Property<int>("Number2")
                        .HasColumnType("integer");

                    b.Property<int>("Number3")
                        .HasColumnType("integer");

                    b.Property<int>("Number4")
                        .HasColumnType("integer");

                    b.Property<int>("Number5")
                        .HasColumnType("integer");

                    b.Property<int>("Number6")
                        .HasColumnType("integer");

                    b.Property<string>("RawRequestPayload")
                        .HasColumnType("text");

                    b.Property<string>("RawResponsePayload")
                        .HasColumnType("text");

                    b.Property<string>("ReasoningExplanation")
                        .HasColumnType("text");

                    b.Property<double?>("Score")
                        .HasColumnType("double precision");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("TargetDrawDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Predictions_CreatedAt");

                    b.HasIndex("Source")
                        .HasDatabaseName("IX_Predictions_Source");

                    b.HasIndex("Number1", "Number2", "Number3", "Number4", "Number5", "Number6")
                        .HasDatabaseName("IX_Predictions_Numbers");

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("PredictLottoNZ.Models.PredictionAccuracy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActualDrawId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExactMatches")
                        .HasColumnType("integer");

                    b.Property<double>("OverallAccuracy")
                        .HasColumnType("double precision");

                    b.Property<int>("PartialMatches")
                        .HasColumnType("integer");

                    b.Property<int>("PredictionId")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("ProximityScore")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ActualDrawId")
                        .HasDatabaseName("IX_PredictionAccuracy_ActualDrawId");

                    b.HasIndex("AnalyzedAt")
                        .HasDatabaseName("IX_PredictionAccuracy_AnalyzedAt");

                    b.HasIndex("PredictionId")
                        .HasDatabaseName("IX_PredictionAccuracy_PredictionId");

                    b.HasIndex("ProviderName")
                        .HasDatabaseName("IX_PredictionAccuracy_ProviderName");

                    b.HasIndex("ProviderName", "AnalyzedAt")
                        .HasDatabaseName("IX_PredictionAccuracy_ProviderName_AnalyzedAt");

                    b.ToTable("PredictionAccuracy");
                });

            modelBuilder.Entity("PredictLottoNZ.Models.TrainingRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<double?>("FinalAccuracy")
                        .HasColumnType("double precision");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ResultingModelVersionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TrainingDataSize")
                        .HasColumnType("integer");

                    b.Property<string>("TrainingMetrics")
                        .HasColumnType("text");

                    b.Property<string>("TrainingParameters")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt")
                        .HasDatabaseName("IX_TrainingRuns_CompletedAt");

                    b.HasIndex("ProviderName")
                        .HasDatabaseName("IX_TrainingRuns_ProviderName");

                    b.HasIndex("ResultingModelVersionId")
                        .HasDatabaseName("IX_TrainingRuns_ResultingModelVersionId");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("IX_TrainingRuns_StartedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_TrainingRuns_Status");

                    b.HasIndex("ProviderName", "Status")
                        .HasDatabaseName("IX_TrainingRuns_ProviderName_Status");

                    b.ToTable("TrainingRuns");
                });

            modelBuilder.Entity("PredictLottoNZ.Models.PredictionAccuracy", b =>
                {
                    b.HasOne("PredictLottoNZ.Models.LottoDraw", "ActualDraw")
                        .WithMany()
                        .HasForeignKey("ActualDrawId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PredictLottoNZ.Models.Prediction", "Prediction")
                        .WithMany("AccuracyMetrics")
                        .HasForeignKey("PredictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActualDraw");

                    b.Navigation("Prediction");
                });

            modelBuilder.Entity("PredictLottoNZ.Models.TrainingRun", b =>
                {
                    b.HasOne("PredictLottoNZ.Models.ModelVersion", "ResultingModelVersion")
                        .WithMany("TrainingRuns")
                        .HasForeignKey("ResultingModelVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ResultingModelVersion");
                });

            modelBuilder.Entity("PredictLottoNZ.Models.ModelVersion", b =>
                {
                    b.Navigation("TrainingRuns");
                });

            modelBuilder.Entity("PredictLottoNZ.Models.Prediction", b =>
                {
                    b.Navigation("AccuracyMetrics");
                });
#pragma warning restore 612, 618
        }
    }
}
